name: Docker build and push

on:
  push:
    branches:
      - 'main'

# Ogranicava da samo jedan job moze da bude pokrenut u isto vreme
concurrency: ci-${{ github.ref }}

jobs:
  docker-build-push:
    name: Build and push latest images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push racunovodstvo-front image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/raf-si-2021/racunovodstvo-front:latest
