export enum Authority {
	ADMIN = 'admin',
	PROFILE = 'profil',
	RECORDS = 'evidencije',
	ACQUISITIONS = 'nabavke',
	SALES = 'prodaja',
	REPORTS = 'izvestaji',
	BOOKKEEPING = 'knjizenje',
	KUF = 'kuf',
	KIF = 'kif',
	ADD_INVOICE = 'dodaj_fakturu',
	ACCOUNT_PLAN = 'kontni_plan',
	BOOKKEEPING_JOURNAL = 'dnevnik_knjizenja',
	MAIN_BOOK = 'glavna_knjiga',
	ADD_CLIENT = 'dodaj_komitenta',
	PAYROLL = 'obracun_zarade',
	BRUTO_BILANS = 'bruto_bilans',
	BILANS_USPEHA = 'bilans_uspeha',
	BILANS_STANJA = 'bilans_stanja',
}
